image: mirror.pvcb.vn/jhipster/jhipster:v6.10.5

variables:
  MVNW_REPOURL: 'https://mirror.pvcb.vn/repository/maven-public-group'
  REGISTRY_URL: 'docker.pvcb.vn'
  CI_REGISTRY_IMAGE: docker.pvcb.vn/pvcombank/managerinternal
  FROM_IMAGE: 'mirror.pvcb.vn/amd64/adoptopenjdk:11-jre-hotspot'
cache:
  key: '$CI_COMMIT_REF_NAME'
  paths:
    - .maven/
stages:
  - check
  - build
  - test
  - analyze
  - package
  - release
  - deploy
before_script:
  # setting maven mirror
  - mkdir -p ~/.m2 && echo -e '<?xml version="1.0" encoding="UTF-8" ?><settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd"><mirrors><mirror><id>PVcomBank</id><name>PVcomBank Maven Repository Manager</name><url>https://mirror.pvcb.vn/repository/maven-public-group</url><mirrorOf>*</mirrorOf></mirror></mirrors></settings>' | tee ~/.m2/settings.xml
  # setting npm mirror
  - echo -e 'registry=https://mirror.pvcb.vn/repository/npm-registry-proxy' | tee ~/.npmrc
  - export MAVEN_USER_HOME=`pwd`/.maven

nohttp:
  stage: check
  script:
    - ./mvnw -ntp checkstyle:check -Dmaven.repo.local=$MAVEN_USER_HOME
#  tags:
#    - vm-runner

maven-compile:
  stage: build
  script:
    - ./mvnw -ntp compile -P-webpack -Dmaven.repo.local=$MAVEN_USER_HOME
  artifacts:
    paths:
      - target/classes/
      - target/generated-sources/
    expire_in: 1 day
#  tags:
#    - vm-runner

# maven-test:
#     # DinD service is required for Testcontainers
#     services:
#         - docker:dind

#     variables:
#         # Instruct Testcontainers to use the daemon of DinD.
#         DOCKER_HOST: 'tcp://docker:2375'
#         # Improve performance with overlayfs.
#         DOCKER_DRIVER: overlay2

#     stage: test
#     script:
#         - ./mvnw -ntp verify -P-webpack -Dmaven.repo.local=$MAVEN_USER_HOME -Dspring.profiles.active=testcontainers
#     artifacts:
#         reports:
#             junit: target/test-results/**/TEST-*.xml
#         paths:
#             - target/test-results
#             - target/jacoco
#         expire_in: 1 day

maven-package:
  stage: package
  script:
    - ./mvnw -ntp verify -Pprod -DskipTests -Dmaven.repo.local=$MAVEN_USER_HOME
  artifacts:
    paths:
      - target/*.jar
      - target/classes
    expire_in: 1 day
#  tags:
#    - vm-runner

docker-push-prod:
  stage: release
  only:
    refs:
      - tags
  except:
    refs:
      - branches
  dependencies:
    - maven-package
  script:
    - >-
      ./mvnw -ntp compile jib:build -Pprod
      -Djib.to.image=$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
      -Djib.to.auth.username=$PVCOMBANK
      -Djib.to.auth.password=$TOKEN
      -Dmaven.repo.local=$MAVEN_USER_HOME
      -Djib.from.image=$FROM_IMAGE
      -Djib.allowInsecureRegistries=true
      -Djib.serialize=true
#  tags:
#    - vm-runner
docker-push-tag:
  stage: release
  only:
    refs:
      - main

  dependencies:
    - maven-package
  script:
    - >-
      ./mvnw -ntp compile jib:build -Pdev,zipkin
      -Djib.to.image=$CI_REGISTRY_IMAGE:dev5
      -Djib.to.auth.username=$PVCOMBANK
      -Djib.to.auth.password=$TOKEN
      -Dmaven.repo.local=$MAVEN_USER_HOME
      -Djib.from.image=$FROM_IMAGE
      -Djib.allowInsecureRegistries=true
      -Djib.serialize=true
#  tags:
#    - vm-runner
